### PR TITLE
IOOS Metadata Profile, Version 1.2

### PR DESCRIPTION
**Pull request by daltonkell**
Creating the IOOS Metadata Profile v1.2 Checker

### CODE REVIEW

**Comment by mwengren** [comment]
@daltonkell @Bobfrat @benjwadams I've been keeping this PR on the back burner for comment, since I wasn't sure where it stood, but before it gets merged, I wanted to give you a heads up that we may have more additions to the profile coming soon.  

Specifically, we sent out guidance to the RAs about how to attribute their ERDDAP datasets for GTS ingest by NDBC.  Some of you may have seen an email from Kathy a few weeks ago.  I attempted to add this to a new version of our 1.2 Profile (you can see [here](https://mwengren.github.io/ioos-metadata/ioos-metadata-profile-v1-2.html#gts-ingest-and-qartod)).  Also, more specific details on using these attributes is [here](https://mwengren.github.io/ioos-metadata/ioos-metadata-profile-v1-2.html#requirements-for-ioos-dataset-gts-ingestion).

Main thing in terms of compliance I think isn't so much checking for the WMO and GTS attributes (since they're not required per se, more required for a specific use case) but rather whether or not we can conditionally check whether the [NDBC/GTS ingest rules](https://mwengren.github.io/ioos-metadata/ioos-metadata-profile-v1-2.html#for-ndbc-to-pull-data-for-a-dataset-to-the-gts) have been followed properly for datasets that include them.  In other words, if a dataset includes `wmo_platform_code` and `gts_ingest`, can we check each data variable for a `gts_ingest` variable attribute and then check for existence of the 'QC rollup' flag, plus other requirements listed?

These checks should be added if possible before we push out a 1.2 checker.

**Comment by mwengren** [comment]
@daltonkell @benjwadams @Bobfrat We're considering revising the Metadata Profile 1.2 guidance I linked to above, so hold off on making any changes to this PR based on what I mentioned above for now.

**Comment by daltonkell** [comment]
Sounds good @mwengren. Once there'a a clearer path forward, we'll clean this up so it best addresses the updated standard.

**Comment by benjwadams** [comment]
Closing.  Using https://github.com/ioos/compliance-checker/tree/ioos_metadata_1_2 to merge into master instead.

**Comment by daltonkell** [comment]
Closing in favor of #743

**Pull request closed without merging**
