### PR TITLE
Remove pkg_resources and go fully to pyproject.toml

### PR DESCRIPTION
**Pull request by ChrisBarker-NOAA**
This PR removes the deprecated pkg_resources.

It also updates to a fully pyproject.toml based build / install, building off the work in: #1024 

Looking now, it seems that #1039 is in fact pretty much the same thing -- wish I'd noticed that earlier!

Sorry to put two things in one PR -- I had done one, and didn't realize how much. was involved in pkg_resources.

Anyway, it would be great if either this or #1039 could be merged.

### CODE REVIEW

**Comment by ChrisBarker-NOAA** [comment]
Hmm -- test failing, due to bad yaml file:

[Invalid workflow file: .github/workflows/default-tests.yml#L24](https://github.com/ChrisBarker-NOAA/compliance-checker/actions/runs/8624698426/workflow)
The workflow is not valid. .github/workflows/default-tests.yml (Line: 24, Col: 22): The expression is not closed. An unescaped ${{ sequence was found, but the closing }} sequence was not found.

I didn't touch that file, so ???

**Comment by jcermauwedu** [comment]
Using `importlib.metadata.entry_points(group=` forces the minimum python to 3.10.   I was struggling in python 3.9.   The workflow `default-tests.yml` may need to drop 3.8 and 3.9.   I will wait for this PR to continue with the pytest fixes in #1056.

**Comment by ChrisBarker-NOAA** [comment]
Now that #1039 has been merged, I'm going to update this. closing for now.

Thanks for the 3.10 hint -- that's where I was testing, but it wasn't clear from the docs which features were added when to the stdlib. I'll use the backported version for older versions.

**Comment by ChrisBarker-NOAA** [comment]
OK -- here it is: #1060

**Pull request closed without merging**
