### PR TITLE
Remove pkg resources

### PR DESCRIPTION
**Pull request by ocefpaf**
[pkg_resources is notoriously slow and problematic](https://github.com/pypa/setuptools/issues/926). This PR tries to remove it from compliance-checker.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@benjwadams there is still one part of `pkg_resources`  that we in the plugins stuff, the `pkg_resources.working_set`, but that one is a bit tricker and I'll leave it to another PR. This one is ready to review.

**Comment by ocefpaf** [comment]
@benjwadams this is hurting me in a setup where I have tons of packages and pkg_resources really drags everything down. While we still have the plugins to deal with, for now, this already helps speed things up. Do you mind taking a look?

**Comment by benjwadams** [comment]
Hi, sorry for the delay.  Will have a look.

**Comment by benjwadams** [comment]
Hi, this should still work with Compliance Checker plugins, correct?

**Comment by benjwadams** [comment]
Just did a test in a pristine environment with `cc-plugin-glider` and it worked.   However, when installing via `pip`, it looks like `packaging` package is missing, so should probably be added to `requirements.txt`.

**Comment by ocefpaf** [comment]
> Just did a test in a pristine environment with `cc-plugin-glider` and it worked.

Cool. The plugin tests are also passing in the CIs. We do need to review the whole plugin system at some point though. But not now 😬 

> However, when installing via `pip`, it looks like `packaging` package is missing, so should probably be added to `requirements.txt`.

Done! I guess some other dependency is pulling it in the CIs b/c it did not fail there.

**Comment by ocefpaf** [comment]
The glider and ugrid plugin failures are an issue upstream I'll try to tackle them this week.

**Comment by ocefpaf** [comment]
With https://github.com/ioos/cc-plugin-glider/pull/42 and https://github.com/ioos/cc-plugin-ugrid/pull/19 this one is green again!

**Comment by jcermauwedu** [comment]
What is the status of trying to include this PR?  I look forward to the reduced warnings generated by the test suite.

**Comment by ocefpaf** [comment]
> What is the status of trying to include this PR? I look forward to the reduced warnings generated by the test suite.

I just rebased it to make it mergeable again.

@benjwadams do you want us to do more testing or are you good with this PR?

**Comment by ChrisBarker-NOAA** [comment]
I just duplicated this work in: #1059 -- not sure if I did a better or worse job. But it would be great if one or the other were merged.

**Comment by jcermauwedu** [comment]
@ChrisBarker-NOAA @ocefpaf @benjwadams I know, I almost did it a 3rd time with this PR(#1056) to fix some of the python tests.  I had to undo those fixes when I remembered they were in this PR.

What can we do to help?

**Comment by ChrisBarker-NOAA** [comment]
What's the blocker to merging this now? Probably better than mine, as mine has a few checks failing -- might as well do this first, and then rebase mine and figure out what's up.

**Comment by ocefpaf** [comment]
> What's the blocker to merging this now? Probably better than mine, as mine has a few checks failing -- might as well do this first, and then rebase mine and figure out what's up.

I'm waiting for Ben's response today and, if he is to busy, I'll self-merge this one. Stay tuned...

**Comment by ChrisBarker-NOAA** [comment]
great, thanks!

-CHB

**Comment by ChrisBarker-NOAA** [comment]
Thanks! Time for me to go update my PR, it *may* address the rest of these issues.

**Pull request merged**
