### PR TITLE
Removal of Wicken

### PR DESCRIPTION
**Pull request by daf**
Wicken/petulant-bear are cool projects, but not necessary for compliance-checker with all the extra they bring along.

This branch is noisy and was having a tough time rebasing due to all the conflict resolution in the merge commit with master, so it'll have to live like this.

I'm not confident tests cover everything, so we'll need people to pull it down and run against datasets they know to work.  Should not require rebuilding your virtenv/conda env as it adds no new deps.

Most of the changes are:
- Remove the `DSPair` concept, replacing with source item (either an xml doc or netcdf Dataset)
- Removal of "beliefs"
- std_checks part of class hierarchy (for overriding)

### CODE REVIEW

**Comment by daf** [comment]
Ah, still haven't fixed the IOOS metadata checker, no tests for that either..

**Comment by lukecampbell** [comment]
Is it true?!

**Comment by daf** [comment]
Oh, it's true.  But needs manual testing plz.

**Comment by lukecampbell** [comment]
I'll have @DanielJMaher take a look

**Comment by lukecampbell** [comment]
All tests pass on a fresh install

```
cf-units==1.0.0
compliance-checker==2.0.0
Jinja2==2.8
lxml==3.5.0
MarkupSafe==0.23
numpy==1.10.4
OWSLib==0.10.3
pbr==1.8.1
py==1.4.31
pyproj==1.9.5.1
pytest==2.8.7
python-dateutil==2.4.2
pytz==2015.7
requests==2.9.1
six==1.10.0
stevedore==0.15
virtualenv==1.11.6
virtualenv-clone==0.2.5
virtualenvwrapper==4.3
wheel==0.24.0
```

This should lead us into #210

**Comment by daf** [comment]
boom

**Comment by lukecampbell** [comment]
I feel bad because @kwilcox and @ocefpaf did a bunch of work the last two days getting petulant-bear and wicken up to par.

**Comment by kwilcox** [comment]
It let me work for 48 hours on CC stuff!

**Comment by ocefpaf** [comment]
> I feel bad because @kwilcox and @ocefpaf did a bunch of work the last two days getting petulant-bear and wicken up to par.

If that work triggered this PR it was worth it :+1:

**Pull request merged**
