### PR TITLE
Introduce plugin system for checkers

### LINKED ISSUE #60: Plugin system for checkers
This is a future issue.

Checkers should be done in a manner to allow independent authoring.  Typical Python approach to this is namespace packages, but caused me so much grief during initial packaging that I don't really want to revisit (nor is it a perfect solution anyway).

This looks like a great alternative: https://github.com/mitsuhiko/pluginbase

### PR DESCRIPTION
**Pull request by daf**
Fixes #60, supercedes #99.

Plugins are based on setuptools using `entry_points`.  This expands on @fxmzb123 's work and allows plugins to be authored as their own simple python packages.

Docs forthcoming (will be added to this PR), here's a quick preview:

The glue to get your plugin recognized by the compliance checker is in your plugin's setup.py.  Include a block like this:
```python
setup(...
    entry_points         = {
        'compliance_checker.suites': [
            'gliderdac = cc_plugin_glider.glider_dac:GliderCheck',
        ]
    }
)
```

The `compliance_checker.suites` is mandatory and is how compliance checker finds your checker.  You can add as many checkers as you'd like in this block which allows you to organize your checkers how you like them - grouped as part of your organization's specific checks, or standalone.

### CODE REVIEW

**Comment by lukecampbell** [comment]
oooohh

**Comment by mhidas** [comment]
@daf What's the status of this PR? Is anyone reviewing it? We (IMOS) haven't looked at it yet, but will try in the next week or two.

**Comment by daf** [comment]
@mhidas expecting @lukecampbell to review. I've just fixed the merge conflicts.

**Comment by daf** [comment]
ioos/cc-plugin-glider@63e31e6 has been updated to reflect this repo's current state wrt gliders.

**Comment by daf** [comment]
Closing in favor of cleaner #173

**Pull request closed without merging**
