### PR TITLE
Using cf_units instead of udunitspy

### LINKED ISSUE #61: Installation problems on windows
I'm trying to test compliance-checker under windows with anaconda. `pip install compliance-checker` is freaking out with: 
```
HDF5_DIR environment variable not set, checking some standard locations ..
checking C:\Users\christopher.rae ...
checking /usr/local ...
checking /sw ...
checking /opt ...
checking /opt/local ...
checking /usr ...
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File  c:\users\christopher.rae\appdata\local\temp\1\pip_build_Christopher.Rae\netCDF4\setup.py", line 208, in <module>
    raise ValueError('did not find HDF5 headers')
ValueError: did not find HDF5 headers
```
@dpsnowden suggests it's probably related to the way PyTables or netcdf4-python were installed in conda for windows, and that @rsignell-usgs may have insight having installed related packages on windows.

### PR DESCRIPTION
**Pull request by lukecampbell**
This PR replaces udunitspy with cf_units, making it possible to run compliance-checker on Windows. The PR passes python2 setup.py test, but more tests are probably needed before merging.

The implementation here followed that of udunitspy, but with some optimizations made possible by the cf_units API.

Unfortunately the file diff shows extra changes ("diff noise") due to leading blank spaces that I can fix if necessary.

Closes #61 (and maybe #62). It does not depend on swig which will make #65 easier.

(Also closes ioos/conda-recipes#225)

### CODE REVIEW

**Comment by ocefpaf** [comment]
:+1:

**Comment by ocefpaf** [comment]
@lukecampbell ping me once you have a new release.  I want to update the conda packages so people can test them on Windows.

**Comment by lukecampbell** [comment]
It looks fine, I'm still a little worried about using ctypes. I've had issues with it in the past. Because it's trying to link a dynamically typed language like Python to a shared library, it's extremely prone to segmentation faults. 

My personal preference is cython, it binds so nicely
https://github.com/lukecampbell/pygsw/blob/master/pygsw/seawater.pyx

**Comment by lukecampbell** [comment]
But, I tried a bunch of cases that I thought of, and had no problems. So let's go forward with it. I'll probably need to update our other projects with cf_units since udunitspy is unmaintained.

Thanks for this and the other work.

**Comment by abirger** [comment]
@ocefpaf , I am following this thread closely, and will try the Windows version as soon as it is available...

**Comment by ocefpaf** [comment]
@abirger as soon as we have a new release I will ping you.  Thanks!

(We have a conda-recipe waiting... https://github.com/ioos/conda-recipes/pull/236)

**Comment by daf** [comment]
@lukecampbell @ocefpaf when I was testing on windows today, I noticed that conda is still trying to pull in udunits - i couldn't tell why.  any ideas?

**Comment by ocefpaf** [comment]
> @lukecampbell @ocefpaf when I was testing on windows today, I noticed
that conda is still trying to pull in udunits - i couldn't tell why. any
ideas?

cf_units still depends on the udunits2 C library. It is just more friendly
than udunitspy+swig.

**Comment by daf** [comment]
Sorry, that's what I missed - it was udunits, not udunitspy.  Carry on...

**Pull request merged**
