### PR TITLE
Pre commit fixup/code cleanup

### PR DESCRIPTION
**Pull request by benjwadams**
Various fixes to black code style, flake8, etc.

### CODE REVIEW

**Comment by benjwadams** [comment]
@ocefpaf, with regards to black, I thought pre-commit steps were taking place to modify code prior to commit?  Please correct me if I'm wrong.

**Comment by benjwadams** [comment]
> ImportError: cannot import name '_unicodefun' from 'click' (/home/runner/.cache/pre-commit/repon4cyg6nb/py_env-python3/lib/python3.10/site-packages/click/__init__.py)

There's this in the logs for the hook for `black`.

**Comment by ocefpaf** [comment]
> @ocefpaf, with regards to black, I thought pre-commit steps were taking place to modify code prior to commit? Please correct me if I'm wrong.

They should if you have it installed in your machine. In the CIs they just check the code but do not commit.

**Comment by ocefpaf** [comment]
> > ImportError: cannot import name '_unicodefun' from 'click' (/home/runner/.cache/pre-commit/repon4cyg6nb/py_env-python3/lib/python3.10/site-packages/click/**init**.py)
> 
> There's this in the logs for the hook for `black`.

Not sure what is happening but you can fix all the pre-commit locally with:

```
pre-commit run --all-files
```

Note that I prefer https://pre-commit.ci/ to the GHA we have but we need someone with admin rights to add it here. (I'm not sure I have enough rights, let me check.)

**Comment by ocefpaf** [comment]
@benjwadams if you are OK merging this now I can finish it in https://github.com/ioos/compliance-checker/pull/928

**Pull request merged**
