### PR TITLE
Test with Python 3.7

### PR DESCRIPTION
**Pull request by ocefpaf**
If I understand the tests correctly the segfault occurs when this line is called:

https://github.com/ioos/compliance-checker/blob/master/compliance_checker/suite.py#L478

I'm not sure if the issue is with `tabulate` or the inputs we are feeding for the table.

### CODE REVIEW

**Comment by benjwadams** [comment]
`tabulate` should be gone now.  See if this works after fixing the merge conflicts.

**Comment by ocefpaf** [comment]
> `tabulate` should be gone now. See if this works after fixing the merge conflicts.

Done!

**Comment by ocefpaf** [comment]
Thanks @Bobfrat for the merge and @benjwadams for the ping.
I probably missed the removal of `tabulate` but do we have a release with that change on PyPI? If not, can we issue a new release?

**Comment by Bobfrat** [comment]
@ocefpaf yes, I think the plan is to issue a patch release once this PR is all set:
https://github.com/ioos/compliance-checker/pull/630

I'll keep you posted.

**Comment by ocefpaf** [comment]
> I'll keep you posted.

Thanks! I'm planing on making the IOOS env Python 3.7 compatible and this is the last package we need.

**Pull request merged**
