### PR TITLE
Free cf_units version

### PR DESCRIPTION
**Pull request by ocefpaf**
cf_units 1.0.0 is out.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@lukecampbell I guess we need to add a better test here.  Travis passed with `cf_units 1.0.0`, but it is clearly not OK.

Do not merge this yet.  I will put some fixes and a test here soon...

**Comment by ocefpaf** [comment]
Jen reported the following error:

```python
[Anaconda2] C:\Users\jennifer.bosch>compliance-checker -h
Could not load acdd = compliance_checker.acdd:ACDDBaseCheck : (cf-units 1.0.0 (c
:\users\jennifer.bosch\appdata\local\continuum\anaconda2\lib\site-packages), Req
uirement.parse('cf-units==0.1.1'))
Could not load cf = compliance_checker.cf.cf:CFBaseCheck : (cf-units 1.0.0 (c:\u
sers\jennifer.bosch\appdata\local\continuum\anaconda2\lib\site-packages), Requir
ement.parse('cf-units==0.1.1'))
Could not load ioos = compliance_checker.ioos:IOOSBaseCheck : (cf-units 1.0.0 (c
:\users\jennifer.bosch\appdata\local\continuum\anaconda2\lib\site-packages), Req
uirement.parse('cf-units==0.1.1'))
usage: compliance-checker-script.py [-h] [--test {}]
                                    [--criteria [{lenient,normal,strict}]]
                                    [--verbose] [-f {text,html,json}]
                                    [-o OUTPUT] [-V]
                                    [dataset_location [dataset_location ...]]

positional arguments:
  dataset_location      Defines the location of the dataset to be checked.

optional arguments:
  -h, --help            show this help message and exit
  --test {}, -t {}, --test= {}, -t= {}
                        Select the Checks you want to perform.
  --criteria [{lenient,normal,strict}], -c [{lenient,normal,strict}]
                        Define the criteria for the checks. Either Strict,
                        Normal, or Lenient. Defaults to Normal.
  --verbose, -v         Increase output. May be specified up to three times.
  -f {text,html,json}, --format {text,html,json}
                        Output format
  -o OUTPUT, --output OUTPUT
                        Output filename
  -V, --version         Display the IOOS Compliance Checker version
                        information.
```


@lukecampbell I thought about adding a call to `compliance-checker -h` in Travis-CI, but that won't raise a non-zero `$?`.  This message is not seen as an error :unamused: inside Travis-CI.

Anyway, the version information is from the `requirements.txt `.  That means this PR fixes the issue.

**Comment by lukecampbell** [comment]
If cf_units fails to appear correctly and causes the various plugins not to be loaded, the tests SHOULD fail on Travis. If this is not the case, we should investigate as to how they are able to be run and pass.

**Comment by ocefpaf** [comment]
In the case above they passed because the cf_units version was passed correctly.

What I meant is that I wanted to add a test to avoid seeing this resurfacing,  but the CLI failure ends returns a `$? = 0` meaning that Travis won't fail by just running `compliance-checker --help`.

So I guess that the CLI script could be updated to do something like `sys.exit(1)` in that case; or we could be smarter and test that logic in travis.  I am :+1: for the former.

**Comment by rsignell-usgs** [comment]
Is there a "dash" vs. "underscore" problem here?
The package is `cf_units`, not `cf-units`

**Comment by ocefpaf** [comment]
Not sure.  It is underscore in the PR,

https://github.com/ioos/compliance-checker/pull/191/files#diff-b4ef698db8ca845e5845c4618278f29aR5

**Comment by rsignell-usgs** [comment]
@lukecampbell ??

**Pull request merged**
