### PR TITLE
Little issues

### PR DESCRIPTION
**Pull request by openSourcerer9000**
Just picking off the smallest github issues:

https://github.com/ioos/compliance-checker/issues/718
https://github.com/ioos/compliance-checker/issues/717
https://github.com/ioos/compliance-checker/issues/785

Updating the wording in the messages didn't break any of the tests that check against hardcoded messages.

### CODE REVIEW

**Comment by daltonkell** [comment]
image

image

image

From the TravisCI build/test logs. We need to determine if this is a CDL issue or a libnetcdf issue with String type variables @openSourcerer9000 @benjwadams

**Comment by ocefpaf** [comment]
Try to pin to libnecdf <4.8.0. I know of at least one issue on Windows. Maybe there are more :-/

**Comment by daltonkell** [comment]
@benjwadams @openSourcerer9000 @ocefpaf I found the issue!

The file standard is different for NetCDF Version 3 and 4 files. Version 4 files can use string type variables. This is fixed by supplying the `-4` flag to `ncgen`:

```
(env38) dalton@ubuntu:~/compliance-checker$ /home/dalton/netcdf-c-build/netcdf-c-4.8.0/netcdf-c-4.8.0/DKELL_BUILD/bin/ncgen -4
-o string_type_variable.nc compliance_checker/tests/data/string_type_variable.cdl
```

**Comment by benjwadams** [comment]
Going to merge this.

**Pull request merged**
