### PR TITLE
Implementation of ACDD 1.3

### PR DESCRIPTION
**Pull request by benjwadams**
Implements #127.

Also adds several new features including the ability to specify version numbers delimited by a colon after the standard name for `compliance-checker` command line tool.  This implements #133 
I.e.
`compliance-checker -t acdd:1.3 file.nc`

Also allows for a 2-tuple with an attribute name and function to be passed into highly recommended, recommended, or suggested attributes, which offers several advantages.  See commit message on   ad716dd

### CODE REVIEW

**Comment by benjwadams** [comment]
Why's Travis having issues?  Can't check due to blocking :(

**Comment by daf** [comment]
Looks like some missing dependencies.

**Comment by benjwadams** [comment]
Hmm.   Just checked via other means and looks like `conda` is erroring due to not finding the `pygeoif` package.  Wasn't aware we were using it for the CI process.

**Comment by daf** [comment]
Likely a dependency of a dependency?

**Comment by benjwadams** [comment]
Looks like the `pygeoif` dependency.  I wanted something that could parse and verify WKT that I didn't need to write by hand, and something that was more lightweight than shapely.  If anyone can think of a more suitable library, I'm all ears.

**Comment by daf** [comment]
Ah sorry, hadn't started reviewing your changes so wasn't aware it was a new dep :)

**Comment by benjwadams** [comment]
@DanielJMaher is actually integrating a number of additional checks into this, so I guess I'll close this PR for the time being.

**Comment by daf** [comment]
Can you maybe extract out the command line additions from the ACDD related stuff?

**Comment by benjwadams** [comment]
Going to rebase a few commits to clean up and create a new branch.

**Comment by daf** [comment]
Since pygeoif showed up on conda, I re-ran the builds.

https://travis-ci.org/ioos/compliance-checker/jobs/117552195

@DanielJMaher I think you should've added a new project wide util file in addition to CF's utils, some of which are pretty specific to CF only stuff.

**Pull request closed without merging**
