### PR TITLE
Adds integration test for HTML output with unicode

### PR DESCRIPTION
**Pull request by lukecampbell**
To verify just run
```
py.test compliance_checker/tests/test_cli.py
```

### CODE REVIEW

**Comment by lukecampbell** [comment]
@benjwadams 

It's going to fail the build, deliberately to mark the build as bad. This is intended since the build is broken, but we just didn't have a test for it.

**Comment by lukecampbell** [comment]
@daf heads up as well.

#254

**Comment by daf** [comment]
Are we going to leave this PR open until fixed?

**Comment by lukecampbell** [comment]
I think what we'll do is have Ben pull down this PR into his branch with the fixes...

**Comment by lukecampbell** [comment]
If it's not fixed soon, I'd like to merge it so we can indicate the build is broken.

**Comment by benjwadams** [comment]
Going to merge as soon as I fix issues with the tests.

**Comment by lukecampbell** [comment]
Ok, finally got travis to get the error right. Travis wasn't actually installing the package so none of the plugins were actually installed.

**Pull request closed without merging**
