### PR TITLE
Remove scoring section from html and standard output

### PR DESCRIPTION
**Pull request by Bobfrat**
@benjwadams this is going into the refactor-scoring branch. This PR simply removes the scoring section of the output (html and standard output, json is unchanged) as a starting point. What's left is the reasoning section that is now divided into the high, medium and low priorities.

### CODE REVIEW

**Comment by Bobfrat** [comment]
@ocefpaf Do you have any insight on why the appveyor build is failing? Looks like its failing here:

```
cmd: conda install --yes conda-build
```

**Comment by ocefpaf** [comment]
I do. I'll send a PR fixing that in a moment.

**Comment by ocefpaf** [comment]
@Bobfrat see #549 

PS: the breakage is unrelated to this PR. It was a regression in the `miniconda` installed in AppVeyor.

**Comment by Bobfrat** [comment]
Thanks @ocefpaf!  I'll pull that into this branch once its built.

**Pull request merged**
