### PR TITLE
Unicode support

### PR DESCRIPTION
**Pull request by lukecampbell**

### CODE REVIEW

**Comment by lukecampbell** [comment]
Fixes #179

**Comment by lukecampbell** [comment]
Also fixes https://github.com/ioos/compliance-checker/issues/178

**Comment by lukecampbell** [comment]
@daf wanna take a look?

**Comment by lukecampbell** [comment]
So, if you look at the reports now, everything for corrective actions is much more intuitive and I fixed a TON of unicode errors. I can't believe the degree to which python 2.* does not like unicode in some of it's most basic builtin functions.

screen shot 2015-11-02 at 1 30 05 pm

**Comment by lukecampbell** [comment]
Gonna merge it.

**Comment by daf** [comment]
:ok_hand:

**Comment by mhidas** [comment]
:+1: Awesome, thanks!

**Pull request merged**
